/** Static route allowlist, kept in sync with src/tools/handlers by an additive test. */
export const HEARTH_TOOL_NAMES = [
  "add_opening",
  "apply_palette",
  "apply_template",
  "arrange_room",
  "cancel_preview",
  "clear_room",
  "compare_variants",
  "confirm_preview",
  "create_room",
  "export_design_board",
  "get_cart",
  "get_checkout_link",
  "get_conflicts",
  "get_design_report",
  "get_product",
  "get_room_details",
  "get_scene_summary",
  "get_selection",
  "load_variant",
  "measure",
  "move_furniture",
  "move_opening",
  "place_furniture",
  "preview_in_room",
  "remove_furniture",
  "remove_opening",
  "save_variant",
  "search_catalog",
  "set_accessibility_mode",
  "set_colorway",
  "set_mode",
  "set_time_of_day",
  "set_view",
  "undo",
  "update_cart",
  "update_room",
] as const;

export const HEARTH_TOOL_NAME_SET: ReadonlySet<string> = new Set(HEARTH_TOOL_NAMES);

